name: Deploy WhoIsWho

on:
  workflow_dispatch:
    inputs:
      rgName:
        description: "Resource Group Name"
        required: true
        default: "whoiswho-deployment-playground"
      rgLocation:
        description: "Resource Location"
        required: true
        default: "westeurope"
      resourcesName:
        description: "Resources Name Main Identifier"
        required: true
        default: "who-is-who-deployment-playground"
      storageAccountName:
        description: "Storage Account Name"
        required: true
        default: "sawiswhpg"

jobs:
  deploy-whoiswho:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets[github.event.inputs.deployment_identity_appregistration] }}

      - name: Deploy Azure Resource Manager (ARM) Template
        id: deployarm
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets['DEPLOYMENT_IDENTITY_SUBSCRIPTION'] }}
          resourceGroupName: ${{ github.event.inputs.rgName }}
          template: ./deployment/azuredeploy.json
          deploymentMode: Incremental
          parameters: rgLocation=${{ github.event.inputs.rgLocation }}
            resourcesName=${{ github.event.inputs.resourcesName }}
            storageAccountName=${{ github.event.inputs.storageAccountName }}
            whoiswho_identity_appid=${{ secrets['WHOISWHO_IDENTITY_APPID'] }}
            whoiswho_identity_password=${{ secrets['WHOISWHO_IDENTITY_PASSWORD'] }}
            whoiswho_identity_tenant=${{ secrets['WHOISWHO_IDENTITY_TENANT'] }}

      - run: echo ${{ steps.deployarm.outputs.whoiswho_app_name }}

      - name: Download WhoIsWho Frontend Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-who-is-who.yml
          name: WhoIsWho.SPA
          branch: master
          path: ./artifacts/whoiswhospa

      - name: Deploy WhoIsWho Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.deployarm.outputs.whoiswho_app_name }}
          package: ./artifacts/whoiswhospa

      - name: Download AzureDataLoader Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-who-is-who.yml
          name: WhoIsWho.DataLoader.Azure
          branch: master
          path: ./artifacts/azuredataloader

      - name: Deploy AzureDataLoader Function
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ steps.deployarm.outputs.whoiswho_azuredataloader_name }}
          package: ./artifacts/azuredataloader

      - name: Download WhoIsWhoDataSync Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-who-is-who.yml
          name: WhoIsWho.DataSync
          branch: master
          path: ./artifacts/datasync

      - name: Deploy WhoIsWhoDataSync Function
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ steps.deployarm.outputs.whoiswho_datasync_name }}
          package: ./artifacts/datasync

      - name: Download WhoIsWhoPortalAPI Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-who-is-who.yml
          name: WhoIsWho.Portal.API
          branch: master
          path: ./artifacts/portalapi

      - name: Deploy WhoIsWhoPortalAPI Function
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ steps.deployarm.outputs.whoiswho_portal_api_name }}
          package: ./artifacts/portalapi

      - name: Finalization of AzureDataLoader settings
        uses: Azure/cli@1.0.4
        with:
          # FunctionApp URL is set here because listkey in the ARM template is not working due to key availability delays altough dependsOn is set
          inlineScript: |
            functionKey=$(az functionapp keys list -g ${{ github.event.inputs.rgName }} -n ${{ steps.deployarm.outputs.whoiswho_datasync_name }} --query "functionKeys.default" -o tsv)
            az functionapp config appsettings set -g ${{ github.event.inputs.rgName }} -n ${{ steps.deployarm.outputs.whoiswho_azuredataloader_name }} --settings "DataLoaderSyncUrl=https://${{ steps.deployarm.outputs.whoiswho_datasync_name }}.azurewebsites.net/api/WhoIsWhoSync?loader={0}&code=$functionKey" --output none
