name: Deploy WhoIsWho

on:
  workflow_dispatch:
    inputs:
      rgName:
        description: "Resource Group Name"
        required: true
        default: "whoiswho-deployment-playground"
      rgLocation:
        description: "Resource Location"
        required: true
        default: "westeurope"
      resourcesName:
        description: "Resources Name Main Identifier"
        required: true
        default: "who-is-who-deployment-playground"

jobs:
  deploy_whoiswho_infrastracture:
    runs-on: ubuntu-latest
    outputs:
      branchName: ${{ steps.extract_branch.outputs.branch }}
      whoiswho_portal_api_hostname: ${{ steps.deployarm.outputs.whoiswho_portal_api_hostname }}
      whoiswho_app_name: ${{ steps.deployarm.outputs.whoiswho_app_name }}
      whoiswho_azuredataloader_name: ${{ steps.deployarm.outputs.whoiswho_azuredataloader_name }}
      whoiswho_datasync_name: ${{ steps.deployarm.outputs.whoiswho_datasync_name }}
      whoiswho_portal_api_name: ${{ steps.deployarm.outputs.whoiswho_portal_api_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPLOYMENT_IDENTITY }}
      - name: Deploy Azure Resource Manager (ARM) Template
        id: deployarm
        uses: Azure/arm-deploy@main
        with:
          scope: resourcegroup
          subscriptionId: ${{ fromJson(secrets.DEPLOYMENT_IDENTITY).subscriptionId }}
          resourceGroupName: ${{ github.event.inputs.rgName }}
          template: ./deployment/azuredeploy.json
          deploymentMode: Incremental
          parameters: rgLocation=${{ github.event.inputs.rgLocation }}
            resourcesName=${{ github.event.inputs.resourcesName }}
            whoiswho_identity_appid=${{ fromJson(secrets.WHOISWHO_IDENTITY_BE).appId }}
            whoiswho_identity_password=${{ fromJson(secrets.WHOISWHO_IDENTITY_BE).password }}
            whoiswho_identity_tenant=${{ fromJson(secrets.WHOISWHO_IDENTITY_BE).tenant }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

  deploy-whoiswho-frontend:
    needs: deploy_whoiswho_infrastracture
    runs-on: ubuntu-latest
    steps:
      - name: Download WhoIsWho Frontend Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-who-is-who.yml
          name: WhoIsWho.SPA
          branch: ${{ steps.extract_branch.outputs.branch }}
          path: ./artifacts/whoiswhospa
          
      - name: WhoIsWho Frontend Config Settings Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'artifacts/whoiswhospa/assets/config/config.default.json'
        env:
          ApiUrlBase: ${{ needs.deploy_whoiswho_infrastracture.outputs.whoiswho_portal_api_hostname }}
          ApiAccessScope: 'http://${{ fromJson(secrets.WHOISWHO_IDENTITY_BE).displayName }}/user_impersonation'
          authentication.clientID: ${{ fromJson(secrets.WHOISWHO_IDENTITY_FE).appId }}
          authentication.authority: 'https://login.microsoftonline.com/${{ fromJson(secrets.WHOISWHO_IDENTITY_FE).tenant }}/'
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPLOYMENT_IDENTITY }}
      - name: Deploy WhoIsWho Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.deploy_whoiswho_infrastracture.outputs.whoiswho_app_name }}
          package: ./artifacts/whoiswhospa

  deploy-whoiswho-azuredataloader:
    needs: deploy_whoiswho_infrastracture
    runs-on: ubuntu-latest
    steps:
      - name: Download AzureDataLoader Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-who-is-who.yml
          name: WhoIsWho.DataLoader.Azure
          branch: ${{ steps.extract_branch.outputs.branch }}
          path: ./artifacts/azuredataloader
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPLOYMENT_IDENTITY }}
      - name: Deploy AzureDataLoader Function
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ needs.deploy_whoiswho_infrastracture.outputs.whoiswho_azuredataloader_name }}
          package: ./artifacts/azuredataloader

  deploy-whoiswho-datasync:
    needs: deploy_whoiswho_infrastracture
    runs-on: ubuntu-latest
    steps:
      - name: Download WhoIsWhoDataSync Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-who-is-who.yml
          name: WhoIsWho.DataSync
          branch: ${{ steps.extract_branch.outputs.branch }}
          path: ./artifacts/datasync
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPLOYMENT_IDENTITY }}
      - name: Deploy WhoIsWhoDataSync Function
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ needs.deploy_whoiswho_infrastracture.outputs.whoiswho_datasync_name }}
          package: ./artifacts/datasync
      
  deploy-whoiswho-portalapi:
    needs: deploy_whoiswho_infrastracture
    runs-on: ubuntu-latest
    steps:
      - name: Download WhoIsWhoPortalAPI Artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          workflow: build-who-is-who.yml
          name: WhoIsWho.Portal.API
          branch: ${{ steps.extract_branch.outputs.branch }}
          path: ./artifacts/portalapi
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPLOYMENT_IDENTITY }}
      - name: Deploy WhoIsWhoPortalAPI Function
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ needs.deploy_whoiswho_infrastracture.outputs.whoiswho_portal_api_name }}
          package: ./artifacts/portalapi

  deploy-finalization:
    needs: [deploy_whoiswho_infrastracture,deploy-whoiswho-frontend,deploy-whoiswho-azuredataloader,deploy-whoiswho-datasync,deploy-whoiswho-portalapi]
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.DEPLOYMENT_IDENTITY }}
      - name: Finalization of AzureDataLoader settings
        uses: Azure/cli@1.0.4
        with:
          # FunctionApp URL is set here because listkey in the ARM template is not working due to key availability delays altough dependsOn is set
          inlineScript: |
            sleep 30s
            functionKey=$(az functionapp keys list -g ${{ github.event.inputs.rgName }} -n ${{ needs.deploy_whoiswho_infrastracture.outputs.whoiswho_datasync_name }} --query "functionKeys.default" -o tsv)
            az functionapp config appsettings set -g ${{ github.event.inputs.rgName }} -n ${{ needs.deploy_whoiswho_infrastracture.outputs.whoiswho_azuredataloader_name }} --settings "DataLoaderSyncUrl=https://${{ needs.deploy_whoiswho_infrastracture.outputs.whoiswho_datasync_name }}.azurewebsites.net/api/WhoIsWhoSync?loader={0}&code=$functionKey" --output none
